// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using T5_PR1.Data;

#nullable disable

namespace T5_PR1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250327221302_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("T5_PR1.Model.EnergyIndicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Any")
                        .HasColumnType("int");

                    b.Property<double>("ConsumGasolina")
                        .HasColumnType("float");

                    b.Property<double>("DemandaElectrica")
                        .HasColumnType("float");

                    b.Property<double>("ProduccioDisponible")
                        .HasColumnType("float");

                    b.Property<double>("ProduccioNeta")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("IndicadorEnergia");
                });

            modelBuilder.Entity("T5_PR1.Model.Simulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CostEnergy")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateSimulation")
                        .HasColumnType("datetime2");

                    b.Property<double>("EnergyNeeded")
                        .HasColumnType("float");

                    b.Property<double>("GeneratedEnergy")
                        .HasColumnType("float");

                    b.Property<double>("PriceEnergy")
                        .HasColumnType("float");

                    b.Property<double>("Rati")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Simulations");
                });

            modelBuilder.Entity("T5_PR1.Model.WaterConsumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Any")
                        .HasColumnType("int");

                    b.Property<string>("Comarca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Consum")
                        .HasColumnType("float");

                    b.Property<int>("Municipi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConsumAigua");
                });
#pragma warning restore 612, 618
        }
    }
}
